<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
	xmlns:html="http://www.w3.org/TR/REC-html40"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap - Kanosa Live</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #333;
						margin: 0;
						padding: 20px;
						background: #f4f7f6;
					}
					.container {
						max-width: 1000px;
						margin: 0 auto;
						background: #fff;
						padding: 40px;
						border-radius: 8px;
						box-shadow: 0 4px 6px rgba(0,0,0,0.1);
					}
					h1 {
						color: #E31E24;
						border-bottom: 2px solid #E31E24;
						padding-bottom: 15px;
						margin-top: 0;
					}
					p.description {
						color: #666;
						font-size: 14px;
						margin-bottom: 30px;
					}
					table {
						width: 100%;
						border-collapse: collapse;
					}
					th {
						text-align: left;
						padding: 12px;
						background: #eee;
						border-bottom: 2px solid #ddd;
						font-size: 13px;
						text-transform: uppercase;
						color: #666;
					}
					td {
						padding: 12px;
						border-bottom: 1px solid #eee;
						font-size: 14px;
					}
					tr:hover td {
						background: #fcfcfc;
					}
					a {
						color: #E31E24;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					.footer {
						margin-top: 40px;
						font-size: 12px;
						color: #999;
						text-align: center;
					}
				</style>
			</head>
			<body>
				<div class="container">
					<h1>XML Sitemap</h1>
					<p class="description">
						This is an XML Sitemap, meant for consumption by search engines like Google or Bing.<br/>
						You can find more information about XML sitemaps on <a href="https://sitemaps.org">sitemaps.org</a>.
				</p>
				<table>
					<tr>
						<th>URL</th>
						<th>Priority</th>
						<th>Change Frequency</th>
						<th>Last Modified</th>
					</tr>
					<xsl:for-each select="sitemap:urlset/sitemap:url">
						<tr>
							<td>
								<xsl:variable name="itemURL">
									<xsl:value-of select="sitemap:loc"/>
								</xsl:variable>
								<a href="{$itemURL}">
									<xsl:value-of select="sitemap:loc"/>
								</a>
							</td>
							<td>
								<xsl:value-of select="sitemap:priority"/>
							</td>
							<td>
								<xsl:value-of select="sitemap:changefreq"/>
							</td>
							<td>
								<xsl:value-of select="sitemap:lastmod"/>
							</td>
						</tr>
					</xsl:for-each>
				</table>
				<div class="footer">
						Generated by Kanosa Live SEO Engine
				</div>
			</div>
		</body>
	</html>
</xsl:template>
</xsl:stylesheet>
